### PR TITLE
Add phpstan/phpstan-strict-rules

### PR DESCRIPTION
**Pull request by szepeviktor**
I can carry a sack of rocks 🗿🗿🗿 but this is mountain! ⛰️ 

From https://github.com/bitExpert/phpstan-magento/pull/64#issuecomment-777251168

### CODE REVIEW

**Comment by szepeviktor** [comment]
Could you help me with the last _Short ternary operator is not allowed_ ?

**Comment by szepeviktor** [comment]
Actually ignoring `- '~^Dynamic call to static method PHPUnit\\Framework\\~'` gets us 3 :) errors.

**Comment by shochdoerfer** [comment]
Will check later.

Would probably rather ignore the tests than ignoring the error.

**Comment by shochdoerfer** [comment]
Fixed the tests and some more minor issues. Thanks.

**Pull request merged**
