### PR TITLE
Use same constraint as latest Magento release

### PR DESCRIPTION
**Pull request by torhoehn**
As described in #42 if I got you right. :)

### CODE REVIEW

**Comment by shochdoerfer** [comment]
Thanks @torhoehn! Great contribution :) Very much appreciated!

**Comment by hostep** [comment]
I don't think this was a good idea.

Are we sure that this package is compatible with phpstan 0.12.3? According to https://github.com/bitexpert/phpstan-magento/commit/c4ac75aba2b338ef423a7c6d5c3012312f8849d0 it probably needs a minimum version of 0.12.18? But I might be wrong.

Then, by constraining it to not be updated to versions higher than 0.12.23 you're making it difficult for people who do actually want to use versions higher than this. I would remove this upper constraint because:

1. Using `bitexpert/phpstan-magento` directly in a Magento project will still work, composer will make sure phpstan is at version 0.12.23 even if `bitexpert/phpstan-magento` allows higher versions
2. People using `bitexpert/phpstan-magento` outside of a Magento project (like I do), will still get the latest phpstan versions with all the new features and bugfixes. I am running version 0.12.50 of phpstan without any issues using version 0.3.0 of `bitexpert/phpstan-magento`

If it turns out this project needs at least version 0.12.18, I suggest we change the constraint to `"phpstan/phpstan": "^0.12.18`. But if it is actually compatible with 0.12.3, then we should change it to `"phpstan/phpstan": "^0.12.3`.

Thoughts?

----

(The [release of 0.4.0](https://github.com/bitExpert/phpstan-magento/releases/tag/v0.4.0) should also mention #43 instead of #40 on the first line 😉 )

**Comment by hostep** [comment]
Thinking about this some more, why do you even want to install `<` as a direct dependency of a Magento project, don't they already handle phpstan natively? What extra features do you get by doing this?

**Comment by hostep** [comment]
Also: the [installation instructions](https://github.com/bitExpert/phpstan-magento#installation) mention to use `bootstrapFiles`, but that feature was introduced in phpstan version [0.12.26](https://github.com/phpstan/phpstan-src/commit/aad1bf888ab7b5808898ee5fe2228bb8bb4e4cf1).

So this PR makes no sense. I think everybody got confused by an invalid request in https://github.com/bitExpert/phpstan-magento/issues/42, no?

**Comment by shochdoerfer** [comment]
@hostep thank you very much for your input and big apologies for not thinking things through completely. I would say the idea came with good intentions but reality hits us hard. I'll open #42 again to have the discussion there on how to solve things.

Just wondering: What is your use case for using `bitexpert/phpstan-magento` outside of a Magento project? Are you talking about module development or about developing something entirely different?

**Comment by hostep** [comment]
No worries! 🙂 

Yes, Magento module development, but not using an entire Magento project. This tools is used for static code analysis and not integration or functional testing. So we only need some part of the source code of some Magento modules and not an entire Magento project to be able to run the static tests.

https://github.com/baldwin-agency/magento2-module-url-data-integrity-checker is the project I'm talking about.

**Pull request merged**
