### PR TITLE
Support for 2.4.4 [WIP]

### PR DESCRIPTION
**Pull request by BrentRobert**
Related to #193

### CODE REVIEW

**Comment by shochdoerfer** [comment]
Thanks for your first contribution! Very much appreciated.

**Comment by BrentRobert** [comment]
Very weird error on the workflow. Need to check what's exactly causing it

**Comment by BrentRobert** [comment]
Pipeline for Magento 2.4.4 will still fail ofcourse, as it's not available publicly.. :)

**Comment by shochdoerfer** [comment]
Then let's wait for next week ;) Thanks so far!

**Comment by shochdoerfer** [comment]
I ran a few tests this morning, the following are my findings:
 - we need to remove `roave/security-advisories` as it will fail for the older Magento versions. Or, as an alternative, we add it in the latest versions during the composer update run in the CI pipeline.
 - we have to skip the PHPStan tests for the Magento versions 2.4.0 & 2.4.1 as they still rely on Composer 1. This causes a CI error because `Composer\Autoload\ClassLoader` does not have a constructor on which our code relies on. Having a check in our code to test for Composer 1 does not seem necessary, so I would simply exclude the PHPStan checks for Magento 2.4.0 and 2.4.1.

**Comment by shochdoerfer** [comment]
Minor addition:
 - Get rid of the `composer.lock` file in the repo. This complicates the CI build due to the different PHP versions and related dependencies.

**Comment by shochdoerfer** [comment]
@BrentRobert I already prepared a few things locally, can proceed with the rest next week, I think.

**Comment by shochdoerfer** [comment]
One more thing (thanks PHPstan!): `ReflectionType::isBuiltin()` got replaced in PHP 8.0 with `ReflectionNamedType::isBuiltin()`

**Comment by shochdoerfer** [comment]
Merged the branch manually since I had to make a few more changes.

**Comment by BrentRobert** [comment]
Thanks @shochdoerfer for your awesome work!

**Pull request closed without merging**
